name: BeiHaiJobReport

on:
  schedule:
    - cron: "0 4 * * *"
    - cron: "0 10 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests lxml
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run misson
      run: |
        python beihaijob.py ${{ secrets.webhook }} ${{ secrets.secret }}
