name: myWeatherBot

on:
  schedule:
    - cron: "30 23 * * *"
    - cron: "30 4 * * *"
    - cron: "30 10 * * *"
  watch:
    types: [started]
jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id  # 自己点的 start
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests lxml
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run misson
      run: |
        python weatherbot.py ${{ secrets.webhook }} ${{ secrets.secret }} ${{ secrets.qweather_key }}
